
# Output level for logging, including package level options
log-level = "info"

# Address defines the rpc server to listen on.
rpc-address = "0.0.0.0:26657"

# Address defines the gRPC server address to bind to.
grpc-address = "0.0.0.0:9090"

# Address defines the API server to listen on.
rest-address = "0.0.0.0:1317"

[chain]

# the network chain ID
chain-id = "fxcore"

# minimum gas limit for a successful transaction
minimum-gas-limit = 30000

# minimum fee for a successful transaction
minimum-fee = ""

# maximum size of a memo transaction passed
max-memo = 256

# no need to verify transaction routers
white-routers = []

# limit the number of extension options
extension-options = 0

# limit the number of non-critical extension options
non-critical-extension_options = 0

# is granter set (default value is 0 for not set, 1 for set)
granter = 0

# is payer set (default value is 0 for not set, 1 for set)
payer = 0

# signer_infos defines the number of signers for the signature
signer-infos = 1

# minimum signature List Length
minimum-signatures = 1

# supported Public Key Types
public-key-type-url = ["/cosmos.crypto.secp256k1.PubKey","/ethermint.crypto.v1.ethsecp256k1.PubKey"]

[redirect]
# Do you need to forward the request
enable = true

# Timeout for forwarding request
time-out-second = 30

check-node-second = 180

[redirect.nodes]
  [redirect.nodes.light]
  
  json-rpc-nodes=[]
  grpc-nodes=[]
  rest-nodes=[]

  [redirect.nodes.full]
  
  json-rpc-nodes=["https://testnet-fx-json.functionx.io:26657"]
  grpc-nodes=["https://testnet-fx-grpc.functionx.io:9090"]
  rest-nodes=["https://testnet-fx-rest.functionx.io:1317"]

  [redirect.nodes.archive]
  json-rpc-nodes=[]
  grpc-nodes=[]
  rest-nodes=[]